spring.application.name=campeonato-futsal
server.port=${PORT:8090}

spring.datasource.url=jdbc:postgresql://maglev.proxy.rlwy.net:46577/railway
spring.datasource.username=postgres
spring.datasource.password=sfLGeGoOBPSppcArYVCgXsGcxpVMvhsu
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false

admin.username=PrefaADM1008
admin.password=EsportePrefa1008