spring.application.name=campeonato-futsal
server.port=${PORT:8090}

spring.datasource.url=jdbc:postgresql://SEU_HOST_AQUI:5432/railway
spring.datasource.username=postgres
spring.datasource.password=SUA_SENHA_AQUI
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false

admin.username=SEU_USUARIO_AQUI
admin.password=SUA_SENHA_AQUI


"Remove credenciais reais do arquivo de exemplo"
