spring.application.name=campeonato-futsal
server.port=8090

# Banco H2 salvo em arquivo (fica dentro da pasta do projeto, em ./data)
spring.datasource.url=jdbc:h2:file:./data/campeonato;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=Andrei
spring.datasource.password=1909Internacional.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.sql.init.mode=never

spring.thymeleaf.cache=false


admin.username=admin
admin.password=admin123
